CC=g++
CLI=HW2_101062124_Cli
SER=HW2_101062124_Ser
LIB=hw2_lib
RTYPE=cpp
CXXFLAG=-std=c++11
all:
	${CC} ${SER}.${RTYPE} ${LIB}.${RTYPE} ${CXXFLAG} -o ${SER}.out
	${CC} ${CLI}.${RTYPE} ${LIB}.${RTYPE} ${CXXFLAG} -o ${CLI}.out

clean:
	rm *.out
